---
apiVersion: v1
kind: Pod
metadata:
  name: kubia
  labels:
    run: kubia
spec:
  serviceAccount: sample-sa
  containers:
  - name: kubia
    image: luksa/kubia:latest
    ports:
    - containerPort: 8080
      protocol: TCP